target: pl_modules.cmamba_module.CryptoMambaModule
params: 
    num_features: 6
    hidden_dims: [60, 64, 128, 30]
    d_states: 64
    layer_density: 4
    loss: 'cross_entropy'
    num_classes: 30
    optimizer: 'adamw'
    lr: 0.001
    window_size: 60
normalize: True
