jumps: 86400
start_date: "2020-01-01"
end_date: "2025-12-02"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/hdfcbank_daily_2020_2025.csv"
train_interval: ["2020-01-01", "2024-01-01"]
val_interval: ["2024-01-01", "2025-01-01"]
test_interval: ["2025-01-01", "2025-12-02"]
additional_features: []
window_size: 60
use_returns: True
binning:
  min_range: -3.5
  max_range: 3.5
  step: 0.25
