data_config: 'classification_daily'
model: 'CMamba_class_v1'

name: 'MambaClassify'
max_epochs: 1000
use_volume: True
additional_features: []

hyperparams:
    optimizer: 'adamw'
    lr: 0.001
    lr_step_size: 100
    lr_gamma: 0.5
    weight_decay: 0.01
